name: devkit
description: A Flutter implementation of the COBI.Bike DevKit

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  rxdart: ^0.22.0
  optional: ^3.0.0
  meta: ^1.1.0
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  test: ^1.6.3
  message_compiler:
    path: ../message_compiler
  build_runner: ^1.3.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui