name: devkit
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: simon <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  rxdart:
  optional:
  meta:

dev_dependencies:
  test: ^1.0.0
  message_compiler:
    path: ../message_compiler
  build_runner:
