name: message_compiler
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: simon <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  analyzer: ^0.36.0
  source_gen: ^0.9.4
  collection: ^1.14.11
  meta: ^1.1.6
  code_builder: ^3.2.0
  build: ^1.1.0
  build_config: ^0.4.0

dev_dependencies:
  test: ^1.0.0
